---
dependency:
  name: gilt
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      ignore: venv
platforms:
  - name: centos7
    command: "/sbin/init"
    image: fiercely/centos7:systemd
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
