---
- name: Converge
  hosts: all
  roles:
    - role: ha-devops-practical
      vars:
        docker_daemon_storage_driver: 'overlay2'  
        docker_daemon_storage_opts: 'overlay2.override_kernel_check=true'